on: 
  push:
    branches: 
      - dsp-add-contributors-readme
    paths-ignore:
      - 'README.md'

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Automatically adds contributors to README
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.DAVID_REPO_TOKEN }}
